vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    product:
      uri_prefix: /assets/images/hp
      upload_destination: '%kernel.project_dir%/public/assets/images/hp'
      namer: Vich\UploaderBundle\Naming\OrignameNamer
