# api/config/packages/vich_uploader.yaml
vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    product:
      uri_prefix: /image/hp
      upload_destination: '%kernel.project_dir%/public/assets/images/hp'
      namer: Vich\UploaderBundle\Naming\OrignameNamer
