# api/config/packages/vich_uploader.yaml
vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    product:
      uri_prefix: /img
      upload_destination: '%kernel.project_dir%/public/assets/img'
      namer: Vich\UploaderBundle\Naming\OrignameNamer
