controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

search_results:
    path: /search/results
    controller: App\Controller\SearchController::results
